Refactor to split dataserver startup into two phases

diff --git a/bin/init_pod_environment b/bin/init_pod_environment
--- a/bin/init_pod_environment
+++ b/bin/init_pod_environment
@@ -111,7 +111,7 @@ then
     cat /opt/pods/base/dataserver/etc/package-includes/777-nti.app.analytics.zcml | sed -e "s|\$SITE_ID|$siteID|g" -e "s|\$SITE_NAME|$sitename|g" -e "s|\$SITE_HOSTNAME|$siteHostname|g" > $podroot/dataserver/etc/package-includes/777-nti.app.analytics.zcml
     chcon -R  system_u:object_r:container_file_t:s0 $podroot
 
-    start_pod_environment $pod
+    start_pod_environment $pod init
     ret=$?
     if [ ! "$ret" -eq 0 ]
     then
@@ -131,7 +131,7 @@ then
     ret=$?
     if [ $ret -ne 0 ]
     then
-      echo "$(date): ABORT! Dataserver failed start." 1>&2
+      echo "$(date): ABORT! Dataserver failed to start." 1>&2
       exit 8
     else
       echo "$(date): The dataserver is accepting requests." 1>&2
@@ -151,8 +151,9 @@ then
     fi
 #    systemd-run --on-active=60 --timer-property=AccuracySec=100ms create_initial_service_account $pod
     systemd-run --on-active=60 --timer-property=AccuracySec=100ms init_splunk_container $pod 1>&2
+    start_dataserver_aux_processes $pod 1>&2
 else
-    start_pod_environment $pod
+    start_pod_environment $pod normal 1>&2
     ret=$?
     if [ ! "$ret" -eq 0 ]
     then
diff --git a/bin/start_pod_environment b/bin/start_pod_environment
--- a/bin/start_pod_environment
+++ b/bin/start_pod_environment
@@ -5,6 +5,12 @@ source /usr/local/lib/nti/nti-container-functions
 
 pod=$1
 podroot=/opt/pods/$pod
+runtype=$2
+
+if [ -z "$runtype" ]
+then
+  runtype="normal"
+fi
 
 echo "$(date): Starting $pod environment" 1>&2
 
@@ -131,6 +137,21 @@ ret=$?
 if [ "$ret" -eq 1 ]
 then
   podman run --pod=$pod --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/splunk/etc:/opt/splunk/etc:rw --volume $podroot/splunk/var:/opt/splunk/var:rw --env SPLUNK_START_ARGS="--accept-license --answer-yes" --entrypoint '[ "entrypoint.sh", "start-service"]' --name $pod-splunk --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/splunk:latest 1>&2
+fi
+
+if [ ! "$runtype" == "init" ]
+then
+  #Waiting for the DS to be up
+  echo "$(date): Checking if the dataserver is up." 1>&2
+  curl -sS --unix-socket /opt/pods/$pod/dataserver/run/dataserver.sock --max-time 90 http://localhost/_ops/ping 1>&2
+  ret=$?
+  if [ $ret -ne 0 ]
+  then
+    echo "$(date): ABORT! Dataserver failed to start." 1>&2
+    exit 8
+  else
+    start_dataserver_aux_processes $pod
+  fi
 fi
 
 chmod go+r $podroot/logs/*.log
diff --git a/lib/nti/nti-container-functions b/lib/nti/nti-container-functions
--- a/lib/nti/nti-container-functions
+++ b/lib/nti/nti-container-functions
@@ -87,7 +87,19 @@ function create_pod (){
       return 14
     fi
   fi
+}
 
+function start_dataserver_aux_processes (){
+  pod=$1
   
-
+  podman container exists $pod-dataserver
+  ret=$?
+  if [ "$ret" -eq 0 ]
+  then
+    echo "$(date): Starting dataserver auxilary processes"
+    podman exec $pod-dataserver /home/ntiuser/buildout/bin/supervisorctl start server:*
+  else
+    echo "$(date): ABORT! No dataserver container is running in the $pod environment."
+    return 16
+  fi
 }
