Add logic to generate and return the invite code during pod setup

diff --git a/bin/init_pod_environment b/bin/init_pod_environment
--- a/bin/init_pod_environment
+++ b/bin/init_pod_environment
@@ -2,9 +2,18 @@
 
 pod=$1
 sitename=$2
-sitehostname=$3
+siteHostname=$3
+adminName=$4
+adminEmail=$5
 
 smtpserver=email-smtp.us-east-1.amazonaws.com
+
+JQ=$(which jq)
+if [ ! -e "$JQ" ]
+then
+  echo "$(date): ABORT! Could not find \'jq\' on the path." 1>&2
+  exit 10
+fi
 
 source /etc/nti/container_versions
 
@@ -45,7 +54,7 @@ then
     rsync --archive --quiet /opt/pods/base/ $podroot 1>&2
     cat /opt/pods/base/dataserver/.boto | sed -e "s|\$ACCESS_KEY_ID|$accesskeyid|g" -e "s|\$SECRET_ACCESS_KEY|$secretaccesskey|g" > $podroot/dataserver/.boto
     cat /opt/pods/base/dataserver/etc/pserve.ini | sed -e "s|\$SMTP_SERVER|$smtpserver|g" -e "s|\$SMTP_USER|$accesskeyid|g" -e "s|\$SMTP_PASSWORD|$smtppass|g" > $podroot/dataserver/etc/pserve.ini
-    cat /opt/pods/base/dataserver/etc/package-includes/777-nti.app.analytics.zcml | sed -e "s|\$SITE_ID|$pod|g" -e "s|\$SITE_NAME|$sitename|g" -e "s|\$SITE_HOSTNAME|$sitehostname|g" > $podroot/dataserver/etc/package-includes/777-nti.app.analytics.zcml
+    cat /opt/pods/base/dataserver/etc/package-includes/777-nti.app.analytics.zcml | sed -e "s|\$SITE_ID|$pod|g" -e "s|\$SITE_NAME|$sitename|g" -e "s|\$SITE_HOSTNAME|$siteHostname|g" > $podroot/dataserver/etc/package-includes/777-nti.app.analytics.zcml
     chcon -R  system_u:object_r:container_file_t:s0 $podroot
     start_pod_environment $pod
     echo -n "$(date): Waiting for dataserver socket" 1>&2
@@ -57,8 +66,25 @@ then
     echo "" 1>&2
     echo "$(date): Dataserver socket available" 1>&2
     echo "$(date): Checking if the dataserver is up." 1>&2
-    curl -sS --unix-socket /opt/pods/$pod/dataserver/run/dataserver.sock --max-time 300 http://localhost/_ops/ping 1>&2
-    echo "$(date): The dataserver is accepting requests." 1>&2
+    curl -sS --unix-socket /opt/pods/$pod/dataserver/run/dataserver.sock --max-time 90 http://localhost/_ops/ping 1>&2
+    ret=$?
+    if [ $ret -ne 0 ]
+    then
+      echo "$(date): ABORT! Dataserver failed start." 1>&2
+      exit 8
+    else
+      echo "$(date): The dataserver is accepting requests." 1>&2
+      echo "$(date): Creating admin invite." 1>&2
+      invite=$(podman exec $pod-dataserver /home/ntiuser/buildout/bin/nti_invite_user "$adminEmail" "$siteHostname" --realname "$adminName" --admin --json 2>/dev/null)
+      ret=$?
+      if [ $ret -ne 0 ]
+      then
+        echo "$(date): ABORT! Failed to create admin invite." 1>&2
+        exit 9
+      else
+        echo $invite | "$JQ" "{admin_invitation: .Links[] | select(.rel==\"redeem\") | .href, host_system: \"$(hostname)\"}"
+      fi
+    fi
 #    systemd-run --on-active=60 --timer-property=AccuracySec=100ms create_initial_service_account $pod
 #    systemd-run --on-active=60 --timer-property=AccuracySec=100ms init_splunk_container $pod
 else
