Detect and handle more error conditions

diff --git a/bin/init_pod_environment b/bin/init_pod_environment
--- a/bin/init_pod_environment
+++ b/bin/init_pod_environment
@@ -5,6 +5,7 @@ sitename=$2
 siteHostname=$3
 adminName=$4
 adminEmail=$5
+extra=$6
 
 if [ -z "$pod" ]
 then
@@ -35,6 +36,14 @@ then
   echo "$(date): ABORT! no admin email specified." 1>&2
   exit 11
 fi
+
+if [ ! -z "$extra" ]
+then
+  echo "$(date): ABORT! extra args detected." 1>&2
+  exit 12
+fi
+
+echo $(/usr/bin/env) 1>&2
 
 smtpserver=email-smtp.us-east-1.amazonaws.com
 
@@ -87,6 +96,12 @@ then
     cat /opt/pods/base/dataserver/etc/package-includes/777-nti.app.analytics.zcml | sed -e "s|\$SITE_ID|$pod|g" -e "s|\$SITE_NAME|$sitename|g" -e "s|\$SITE_HOSTNAME|$siteHostname|g" > $podroot/dataserver/etc/package-includes/777-nti.app.analytics.zcml
     chcon -R  system_u:object_r:container_file_t:s0 $podroot
     start_pod_environment $pod
+    ret=$?
+    if [ ! "$ret" -eq 0 ]
+    then
+      echo "$(date): $pod environment startup failed" 1>&2
+      exit $ret
+    fi
     echo -n "$(date): Waiting for dataserver socket" 1>&2
     until [ -e "$podroot/dataserver/run/dataserver.sock" ]
     do
diff --git a/bin/start_pod_environment b/bin/start_pod_environment
--- a/bin/start_pod_environment
+++ b/bin/start_pod_environment
@@ -68,7 +68,16 @@ then
     chcon -R  system_u:object_r:container_file_t:s0 "$podroot/dataserver/run"
   fi
   podman run --pod=$pod --volume $podroot/dataserver/.boto:/home/ntiuser/.boto:ro --volume $podroot/dataserver/etc:/home/ntiuser/buildout/etc:rw --volume $podroot/dataserver/data:/home/ntiuser/buildout/data:rw --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/dataserver/maildir:/home/ntiuser/buildout/var/maildir:rw --volume $podroot/dataserver/run:/home/ntiuser/buildout/var/run:rw --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --name $pod-dataserver --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/dataserver:$dataserver 1>&2
-  echo "$(date): $pod-dataserver container running" 1>&2
+  ret=$?
+  if [ "$ret" -eq 0 ]
+  then
+    echo "$(date): $pod-dataserver container running" 1>&2
+  else
+    echo "$(date): ABORT! Failed to start $pod-dataserver" 1>&2
+    echo "$(date): Cleaning up $pod-dataserver."
+    podman rm $pod-dataserver 1>&2
+    exit 13
+  fi
 fi
 
 podman container exists $pod-redis
