Redirect output from stdout to stderr

diff --git a/bin/start_pod_environment b/bin/start_pod_environment
--- a/bin/start_pod_environment
+++ b/bin/start_pod_environment
@@ -5,13 +5,13 @@ pod=$1
 source /etc/nti/container_versions
 source /usr/local/lib/nti/nti-container-functions
 
-echo "Starting $pod environment"
+echo "Starting $pod environment" 1>&2
 
 podroot=/opt/pods/$pod
 if [ ! -e "$podroot" ]
 then
-  echo "Creating $podroot"
-  mkdir -p $podroot
+  echo "Creating $podroot" 1>&2
+  mkdir -p $podroot/
 fi
 
 t0=$(grep -e "$podroot" /proc/mounts)
@@ -19,16 +19,16 @@ if [ -z "$t0" ]
 then
   if [ -e "/opt/volumes/$pod.img" ]
   then
-    echo "Mounting $podroot"
-    mount -o loop,rw /opt/volumes/$pod.img $podroot
+    echo "Mounting $podroot" 1>&2
+    mount -o loop,rw /opt/volumes/$pod.img $podroot 1>&2
     ret=$?
     if [ $ret -ne 0 ]
     then
-        echo "ABORT! Attempt to mount $pod data volume failed"
+        echo "ABORT! Attempt to mount $pod data volume failed" 1>&2
         exit 7
     fi
   else
-    echo "ABORT! $pod data volume missing"
+    echo "ABORT! $pod data volume missing" 1>&2
     exit 6
   fi
 fi
@@ -37,60 +37,60 @@ podman pod exists $pod
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  echo "Creating $pod pod"
-  podman pod create --name $pod --hostname $pod.nti
-  podman pod start $pod
+  echo "Creating $pod pod" 1>&2
+  podman pod create --name $pod --hostname $pod.nti 1>&2
+  podman pod start $pod 1>&2
 fi
 
-add_CNAME $pod
+add_CNAME $pod 1>&2
 
 podman container exists $pod-solr
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/solr-data:/opt/solr/conf/nti/data:rw --name $pod-solr --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/solr
+  podman run --pod=$pod --volume $podroot/solr-data:/opt/solr/conf/nti/data:rw --name $pod-solr --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/solr 1>&2
 fi
 
 podman container exists $pod-rsyslog
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/logs:/var/log:rw --name $pod-rsyslog --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/rsyslog:latest
+  podman run --pod=$pod --volume $podroot/logs:/var/log:rw --name $pod-rsyslog --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/rsyslog:latest 1>&2
 fi
 
 podman container exists $pod-haproxy
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/run:/run:rw --name $pod-haproxy --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/haproxy
+  podman run --pod=$pod --volume $podroot/run:/run:rw --name $pod-haproxy --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/haproxy 1>&2
 fi
 
 podman container exists $pod-haproxy-exporter
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/run:/run:rw --name $pod-haproxy-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/haproxy-exporter
+  podman run --pod=$pod --volume $podroot/run:/run:rw --name $pod-haproxy-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/haproxy-exporter 1>&2
 fi
 
 podman container exists $pod-nginx
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --volume $podroot/logs/nginx:/var/log/nginx:rw --name $pod-nginx --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/nginx
+  podman run --pod=$pod --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --volume $podroot/logs/nginx:/var/log/nginx:rw --name $pod-nginx --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/nginx 1>&2
 fi
 
 podman container exists $pod-redis
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/redis/:/var/lib/redis:rw --volume $podroot/logs/:/var/log/redis:rw --name $pod-redis --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/redis
+  podman run --pod=$pod --volume $podroot/redis/:/var/lib/redis:rw --volume $podroot/logs/:/var/log/redis:rw --name $pod-redis --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/redis 1>&2
 fi
 
 podman container exists $pod-statsd-exporter
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --name $pod-statsd-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/statsd-exporter:latest
+  podman run --pod=$pod --name $pod-statsd-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/statsd-exporter:latest 1>&2
 fi
 
 podman container exists $pod-web-service
@@ -99,9 +99,9 @@ if [ "$ret" -eq 1 ]
 then
   if [ -e "$podroot/overrides/webservice" ]
   then
-    podman run --pod=$pod --volume $podroot/overrides/webservice:/opt/nextthought/overrides:rw --volume $podroot/logs:/var/log:rw --name $pod-web-service --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/web-service:$webservice
+    podman run --pod=$pod --volume $podroot/overrides/webservice:/opt/nextthought/overrides:rw --volume $podroot/logs:/var/log:rw --name $pod-web-service --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/web-service:$webservice 1>&2
   else
-    podman run --pod=$pod --volume $podroot/logs:/var/log:rw --name $pod-web-service --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/web-service:$webservice
+    podman run --pod=$pod --volume $podroot/logs:/var/log:rw --name $pod-web-service --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/web-service:$webservice 1>&2
   fi
 fi
 
@@ -109,21 +109,21 @@ podman container exists $pod-dataserver
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/dataserver/.boto:/home/ntiuser/.boto:ro --volume $podroot/dataserver/etc:/home/ntiuser/buildout/etc:rw --volume $podroot/dataserver/data:/home/ntiuser/buildout/data:rw --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/dataserver/maildir:/home/ntiuser/buildout/var/maildir:rw --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --name $pod-dataserver --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/dataserver:$dataserver
+  podman run --pod=$pod --volume $podroot/dataserver/.boto:/home/ntiuser/.boto:ro --volume $podroot/dataserver/etc:/home/ntiuser/buildout/etc:rw --volume $podroot/dataserver/data:/home/ntiuser/buildout/data:rw --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/dataserver/maildir:/home/ntiuser/buildout/var/maildir:rw --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --name $pod-dataserver --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/dataserver:$dataserver 1>&2
 fi
 
 podman container exists $pod-node-exporter
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --name $pod-node-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/node-exporter:latest
+  podman run --pod=$pod --name $pod-node-exporter --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/prometheus/node-exporter:latest 1>&2
 fi
 
 podman container exists $pod-splunk
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  podman run --pod=$pod --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/splunk/etc:/opt/splunk/etc:rw --volume $podroot/splunk/var:/opt/splunk/var:rw --env SPLUNK_START_ARGS="--accept-license --answer-yes" --entrypoint '[ "entrypoint.sh", "start-service"]' --name $pod-splunk --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/splunk:latest
+  podman run --pod=$pod --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/splunk/etc:/opt/splunk/etc:rw --volume $podroot/splunk/var:/opt/splunk/var:rw --env SPLUNK_START_ARGS="--accept-license --answer-yes" --entrypoint '[ "entrypoint.sh", "start-service"]' --name $pod-splunk --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/splunk:latest 1>&2
 fi
 
 chmod go+r $podroot/logs/*.log
