Add validating the presence of required args

diff --git a/bin/start_pod_environment b/bin/start_pod_environment
--- a/bin/start_pod_environment
+++ b/bin/start_pod_environment
@@ -8,6 +8,12 @@ podroot=/opt/pods/$pod
 logroot=/opt/pods/logs/$pod.nti
 runtype=$2
 
+if [ -z "$pod" ]
+then
+  echo "$(date): ABORT! no pod id specified." 1>&2
+  exit 11
+fi
+
 if [ -e "$podroot/environment" ]
 then
   source $podroot/environment
diff --git a/bin/transfer_pod b/bin/transfer_pod
--- a/bin/transfer_pod
+++ b/bin/transfer_pod
@@ -3,6 +3,18 @@
 pod=$1
 dest=$2
 
+if [ -z "$pod" ]
+then
+  echo "$(date): ABORT! no pod id specified." 1>&2
+  exit 11
+fi
+
+if [ -z "$dest" ]
+then
+  echo "$(date): ABORT! no destination host specified." 1>&2
+  exit 11
+fi
+
 shutdown_pod_environment $pod
 
 tar -C /opt/volumes/ -czvSpf - $pod.img | ssh $dest tar -C  /opt/volumes/ -xzSpf -
