Add logging and time stamps

diff --git a/bin/start_pod_environment b/bin/start_pod_environment
--- a/bin/start_pod_environment
+++ b/bin/start_pod_environment
@@ -5,12 +5,12 @@ pod=$1
 source /etc/nti/container_versions
 source /usr/local/lib/nti/nti-container-functions
 
-echo "Starting $pod environment" 1>&2
+echo "$(date): Starting $pod environment" 1>&2
 
 podroot=/opt/pods/$pod
 if [ ! -e "$podroot" ]
 then
-  echo "Creating $podroot" 1>&2
+  echo "$(date): Creating $podroot" 1>&2
   mkdir -p $podroot/
 fi
 
@@ -19,16 +19,16 @@ if [ -z "$t0" ]
 then
   if [ -e "/opt/volumes/$pod.img" ]
   then
-    echo "Mounting $podroot" 1>&2
+    echo "$(date): Mounting $podroot" 1>&2
     mount -o loop,rw /opt/volumes/$pod.img $podroot 1>&2
     ret=$?
     if [ $ret -ne 0 ]
     then
-        echo "ABORT! Attempt to mount $pod data volume failed" 1>&2
+        echo "$(date): ABORT! Attempt to mount $pod data volume failed" 1>&2
         exit 7
     fi
   else
-    echo "ABORT! $pod data volume missing" 1>&2
+    echo "$(date): ABORT! $pod data volume missing" 1>&2
     exit 6
   fi
 fi
@@ -37,7 +37,7 @@ podman pod exists $pod
 ret=$?
 if [ "$ret" -eq 1 ]
 then
-  echo "Creating $pod pod" 1>&2
+  echo "$(date): Creating $pod pod" 1>&2
   podman pod create --name $pod --hostname $pod.nti 1>&2
   podman pod start $pod 1>&2
 fi
@@ -48,6 +48,7 @@ podman container exists $pod-dataserver
 ret=$?
 if [ "$ret" -eq 1 ]
 then
+  echo "$(date): Starting $pod-dataserver container" 1>&2
   if [ ! -e "$podroot/dataserver/data" ]
   then
     mkdir -p "$podroot/dataserver/data"
@@ -67,6 +68,7 @@ then
     chcon -R  system_u:object_r:container_file_t:s0 "$podroot/dataserver/run"
   fi
   podman run --pod=$pod --volume $podroot/dataserver/.boto:/home/ntiuser/.boto:ro --volume $podroot/dataserver/etc:/home/ntiuser/buildout/etc:rw --volume $podroot/dataserver/data:/home/ntiuser/buildout/data:rw --volume $podroot/logs:/home/ntiuser/buildout/var/log:rw --volume $podroot/dataserver/maildir:/home/ntiuser/buildout/var/maildir:rw --volume $podroot/dataserver/run:/home/ntiuser/buildout/var/run:rw --volume $podroot/assets:/srv/assets:rw --volume $podroot/content:/srv/content:rw --name $pod-dataserver --detach --rm docker://556717414764.dkr.ecr.us-east-1.amazonaws.com/platform/dataserver:$dataserver 1>&2
+  echo "$(date): $pod-dataserver container running" 1>&2
 fi
 
 podman container exists $pod-redis
@@ -145,3 +147,4 @@ then
 fi
 
 chmod go+r $podroot/logs/*.log
+echo "$(date): $pod environment is running" 1>&2
